# Generated by Django 3.0.4 on 2020-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name1', models.CharField(max_length=50)),
                ('last_name1', models.CharField(max_length=50)),
                ('phone_number1', models.CharField(max_length=40)),
                ('id_order1', models.CharField(max_length=30)),
                ('order_number1', models.CharField(max_length=30)),
            ],
        ),
    ]
